theme: jekyll-theme-cayman

name: RCF Shop API
title: RCF Shop API
descripton: F
show_downloads: true

# Setup
title:        RCF Shop API
tagline:      Created for the Shopify Summer 2019 Developer Intern Challenge.
locale:       "en"

# About/contact
author:
  name:       Ryan Fleck
  url:        http://ryanfleck.github.io
