CREATE TABLE products (
	title VARCHAR(50) NOT NULL,
	price DECIMAL(4,2) NOT NULL,
	inventory_count INT NOT NULL
);

insert into products (title, price, inventory_count) values ('Forget Baghdad: Jews and Arabs - The Iraqi Connection', 10.01, 372);
insert into products (title, price, inventory_count) values ('Hoodoo Ann', 44.56, 818);
insert into products (title, price, inventory_count) values ('Broken Kingdom', 32.72, 709);
insert into products (title, price, inventory_count) values ('Code Name: The Cleaner', 64.01, 842);
insert into products (title, price, inventory_count) values ('Deep Blue Sea, The', 8.74, 568);
insert into products (title, price, inventory_count) values ('Wings of Hope (Julianes Sturz in den Dschungel)', 21.93, 720);
insert into products (title, price, inventory_count) values ('Mr Hublot', 32.7, 0);
insert into products (title, price, inventory_count) values ('Guy', 44.2, 0);
insert into products (title, price, inventory_count) values ('Duplicity', 29.52, 235);
insert into products (title, price, inventory_count) values ('Evil of Frankenstein, The', 32.87, 276);
insert into products (title, price, inventory_count) values ('Stereo', 38.93, 478);
insert into products (title, price, inventory_count) values ('Look Who''s Talking', 8.19, 693);
insert into products (title, price, inventory_count) values ('Delusions of Grandeur (La folie des grandeurs)', 7.03, 131);
insert into products (title, price, inventory_count) values ('Wee Willie Winkie', 23.1, 0);
insert into products (title, price, inventory_count) values ('Letter, The', 26.62, 330);
insert into products (title, price, inventory_count) values ('Rink, The', 68.46, 0);
insert into products (title, price, inventory_count) values ('Valley of the Bees (Údolí vcel)', 39.06, 0);
insert into products (title, price, inventory_count) values ('Is It Easy to be Young?', 27.36, 0);
insert into products (title, price, inventory_count) values ('3 Idiots', 9.47, 0);
insert into products (title, price, inventory_count) values ('Devour', 52.03, 0);
insert into products (title, price, inventory_count) values ('Until the End of the World (Bis ans Ende der Welt)', 26.15, 907);
insert into products (title, price, inventory_count) values ('Sergio', 45.46, 975);
insert into products (title, price, inventory_count) values ('Sound and the Fury, The', 22.45, 0);
insert into products (title, price, inventory_count) values ('Rain', 65.45, 803);
insert into products (title, price, inventory_count) values ('Boogie (Boogie, el aceitoso)', 55.14, 992);
insert into products (title, price, inventory_count) values ('Village People', 33.28, 806);
insert into products (title, price, inventory_count) values ('Out for a Kill', 25.45, 945);
insert into products (title, price, inventory_count) values ('Cottage, The', 6.08, 950);
insert into products (title, price, inventory_count) values ('Girl from the Naked Eye, The', 45.05, 197);
insert into products (title, price, inventory_count) values ('Afterglow', 41.52, 857);
insert into products (title, price, inventory_count) values ('Eva (a.k.a. Eve)', 33.47, 339);
insert into products (title, price, inventory_count) values ('Games of Love and Chance (L''esquive)', 12.75, 363);
insert into products (title, price, inventory_count) values ('187 (One Eight Seven)', 23.15, 805);
insert into products (title, price, inventory_count) values ('Prey, The (La proie)', 32.42, 235);
insert into products (title, price, inventory_count) values ('Bulldog Drummond Escapes', 3.48, 328);
insert into products (title, price, inventory_count) values ('Philadelphia Story, The', 7.36, 694);
insert into products (title, price, inventory_count) values ('Blood Spattered Bride, The (La novia ensangrentada)', 12.16, 521);
insert into products (title, price, inventory_count) values ('American Friends', 23.04, 0);
insert into products (title, price, inventory_count) values ('Stratton Story, The', 7.55, 802);
insert into products (title, price, inventory_count) values ('Manitou, The', 68.85, 991);
insert into products (title, price, inventory_count) values ('Adventure in Space and Time, An', 54.4, 654);
insert into products (title, price, inventory_count) values ('Slammin'' Salmon, The', 5.13, 186);
insert into products (title, price, inventory_count) values ('Blue Umbrella, The', 35.98, 241);
insert into products (title, price, inventory_count) values ('Nobody''s Fool', 19.97, 748);
insert into products (title, price, inventory_count) values ('Crank: High Voltage', 28.85, 54);
insert into products (title, price, inventory_count) values ('Wrong Turn 5: Bloodlines', 6.59, 42);
insert into products (title, price, inventory_count) values ('Dead Poets Society', 15.69, 318);
insert into products (title, price, inventory_count) values ('Kiss Me Kate', 23.24, 733);
insert into products (title, price, inventory_count) values ('Sleepwalking', 19.79, 662);
insert into products (title, price, inventory_count) values ('Thieves by Law (Ganavim Ba Hok)', 27.41, 0);
insert into products (title, price, inventory_count) values ('Dry White Season, A', 35.09, 854);
insert into products (title, price, inventory_count) values ('Manuel on the Island of Wonders (Manoel dans l''île des merveilles)', 8.3, 687);
insert into products (title, price, inventory_count) values ('Dracula 2000', 37.35, 0);
insert into products (title, price, inventory_count) values ('Two Hands', 57.58, 483);
insert into products (title, price, inventory_count) values ('FairyTale: A True Story', 68.92, 0);
insert into products (title, price, inventory_count) values ('Shed No Tears (Känn ingen sorg)', 50.66, 0);
insert into products (title, price, inventory_count) values ('Your Vice is a Locked Room and Only I Have the Key', 65.93, 315);
insert into products (title, price, inventory_count) values ('Ugly, The', 30.65, 570);
insert into products (title, price, inventory_count) values ('Medora', 17.93, 0);
insert into products (title, price, inventory_count) values ('Strayed (égarés, Les)', 57.11, 229);
insert into products (title, price, inventory_count) values ('Terror on a Train (Time Bomb)', 23.62, 586);
insert into products (title, price, inventory_count) values ('Stranger in the House', 38.85, 907);
insert into products (title, price, inventory_count) values ('Good Men, Good Women (Hao nan hao nu)', 26.11, 591);
insert into products (title, price, inventory_count) values ('Tali-Ihantala 1944', 5.41, 324);
insert into products (title, price, inventory_count) values ('If a Man Answers', 25.83, 675);
insert into products (title, price, inventory_count) values ('Wrecking Crew, The', 59.09, 122);
insert into products (title, price, inventory_count) values ('Thing with Two Heads, The', 57.57, 270);
insert into products (title, price, inventory_count) values ('Christmas Carol, A', 35.45, 696);
insert into products (title, price, inventory_count) values ('Jupiter Ascending', 5.23, 420);
insert into products (title, price, inventory_count) values ('Family Guy Presents: It''s a Trap', 8.61, 73);
insert into products (title, price, inventory_count) values ('Master and Commander: The Far Side of the World', 37.38, 119);
insert into products (title, price, inventory_count) values ('Looking for Comedy in the Muslim World', 49.66, 0);
insert into products (title, price, inventory_count) values ('Resident Evil: Retribution', 12.67, 213);
insert into products (title, price, inventory_count) values ('Scarlet Pimpernel, The', 28.4, 423);
insert into products (title, price, inventory_count) values ('That Old Feeling', 7.86, 997);
insert into products (title, price, inventory_count) values ('Behind the Screen', 58.47, 830);
insert into products (title, price, inventory_count) values ('Jersey Girl', 23.12, 844);
insert into products (title, price, inventory_count) values ('Stereo', 20.62, 162);
insert into products (title, price, inventory_count) values ('Red State', 23.27, 104);
insert into products (title, price, inventory_count) values ('Quarantine 2: Terminal', 65.71, 0);
insert into products (title, price, inventory_count) values ('Wild Hunt, The', 21.77, 755);
insert into products (title, price, inventory_count) values ('Voodoo Tiger', 42.03, 907);
insert into products (title, price, inventory_count) values ('Forger, The', 29.78, 0);
insert into products (title, price, inventory_count) values ('Crimes Against Humanity', 20.12, 862);
insert into products (title, price, inventory_count) values ('Trojan Women, The', 30.51, 88);
insert into products (title, price, inventory_count) values ('When Animals Dream (Når dyrene drømmer)', 45.63, 0);
insert into products (title, price, inventory_count) values ('Glee: The 3D Concert Movie', 69.26, 0);
insert into products (title, price, inventory_count) values ('Jolene', 17.12, 0);
insert into products (title, price, inventory_count) values ('Mindscape of Alan Moore, The', 22.63, 678);
insert into products (title, price, inventory_count) values ('Saving General Yang', 69.73, 751);
insert into products (title, price, inventory_count) values ('Beware of a Holy Whore (Warnung vor einer heiligen Nutte)', 33.43, 0);
insert into products (title, price, inventory_count) values ('Fathers'' Day', 57.7, 0);
insert into products (title, price, inventory_count) values ('French Cancan', 15.89, 656);
insert into products (title, price, inventory_count) values ('Iron Man', 63.19, 446);
insert into products (title, price, inventory_count) values ('The Overnight', 35.23, 125);
insert into products (title, price, inventory_count) values ('Mr. Denning Drives North', 38.87, 0);
insert into products (title, price, inventory_count) values ('Anna and the King of Siam', 6.04, 352);
insert into products (title, price, inventory_count) values ('Snow and Ashes', 67.03, 928);
insert into products (title, price, inventory_count) values ('Suspect, The', 30.71, 953);
insert into products (title, price, inventory_count) values ('That''s The Way I Like It (a.k.a. Forever Fever)', 16.31, 167);
insert into products (title, price, inventory_count) values ('Crime of Father Amaro, The (Crimen del padre Amaro, El)', 6.5, 520);
insert into products (title, price, inventory_count) values ('American Gothic', 13.21, 804);
insert into products (title, price, inventory_count) values ('Candidate, The', 31.46, 411);
insert into products (title, price, inventory_count) values ('Old Yeller', 59.13, 502);
insert into products (title, price, inventory_count) values ('Blonde Crazy', 9.91, 851);
insert into products (title, price, inventory_count) values ('Talking Picture, A (Um Filme Falado)', 50.51, 964);
insert into products (title, price, inventory_count) values ('Dracula A.D. 1972', 22.69, 0);
insert into products (title, price, inventory_count) values ('Pigs with a P.38', 35.62, 431);
insert into products (title, price, inventory_count) values ('Eleventh Year, The (Odinnadtsatyy) ', 23.55, 0);
insert into products (title, price, inventory_count) values ('Grand Maneuver, The (Les grandes manoeuvres)', 19.01, 667);
insert into products (title, price, inventory_count) values ('Albino Farm', 65.21, 0);
insert into products (title, price, inventory_count) values ('Nothing Sacred', 64.58, 742);
insert into products (title, price, inventory_count) values ('He Who Dares', 8.24, 0);
insert into products (title, price, inventory_count) values ('To the Devil a Daughter', 7.44, 133);
insert into products (title, price, inventory_count) values ('Hawaii, Oslo', 47.47, 745);
insert into products (title, price, inventory_count) values ('Unspeakable Act, The', 21.64, 0);
insert into products (title, price, inventory_count) values ('Red Sorghum (Hong gao liang)', 9.42, 618);
insert into products (title, price, inventory_count) values ('French Roast', 37.6, 0);
insert into products (title, price, inventory_count) values ('Employee of the Month', 18.08, 0);
insert into products (title, price, inventory_count) values ('Thunderpants', 37.12, 337);
insert into products (title, price, inventory_count) values ('Invasion of the Body Snatchers', 54.58, 0);
insert into products (title, price, inventory_count) values ('Lonely Street', 38.01, 313);
insert into products (title, price, inventory_count) values ('Star Maker, The (Uomo delle stelle, L'')', 21.45, 845);
insert into products (title, price, inventory_count) values ('Ace Ventura: When Nature Calls', 61.7, 487);
insert into products (title, price, inventory_count) values ('Monty Python: Almost the Truth - Lawyers Cut', 32.7, 778);
insert into products (title, price, inventory_count) values ('Sunset Park', 15.92, 0);
insert into products (title, price, inventory_count) values ('They Call Me Renegade', 58.67, 817);
insert into products (title, price, inventory_count) values ('Cursed', 24.62, 0);
insert into products (title, price, inventory_count) values ('Kid Cannabis', 43.22, 364);
insert into products (title, price, inventory_count) values ('Mafioso', 43.72, 0);
insert into products (title, price, inventory_count) values ('I Wake Up Screaming', 42.23, 507);
insert into products (title, price, inventory_count) values ('Wicked Blood', 42.03, 0);
insert into products (title, price, inventory_count) values ('Moine, Le (Monk, The)', 63.28, 230);
insert into products (title, price, inventory_count) values ('Go Tigers!', 41.36, 40);
insert into products (title, price, inventory_count) values ('Cost of Living, The (Le coût de la vie)', 12.15, 0);
insert into products (title, price, inventory_count) values ('Harry Potter and the Prisoner of Azkaban', 26.04, 293);
insert into products (title, price, inventory_count) values ('Chuck & Buck', 21.56, 834);
insert into products (title, price, inventory_count) values ('Tamara', 20.19, 414);
insert into products (title, price, inventory_count) values ('Major Movie Star', 43.02, 638);
insert into products (title, price, inventory_count) values ('Beck - Rum 302', 25.27, 84);
insert into products (title, price, inventory_count) values ('Citizen Kane', 61.09, 738);
insert into products (title, price, inventory_count) values ('Cat from Outer Space, The', 38.69, 959);
insert into products (title, price, inventory_count) values ('You''re Not You', 21.23, 845);
insert into products (title, price, inventory_count) values ('Dream Lover', 58.82, 64);
insert into products (title, price, inventory_count) values ('U2 3D', 16.33, 769);
insert into products (title, price, inventory_count) values ('Fear City', 58.42, 0);
insert into products (title, price, inventory_count) values ('Madame Bovary', 62.36, 105);
insert into products (title, price, inventory_count) values ('Upside of Anger, The', 55.25, 702);
insert into products (title, price, inventory_count) values ('Siegfried & Roy: The Magic Box', 50.23, 489);
insert into products (title, price, inventory_count) values ('Retribution (Sakebi)', 59.26, 339);
insert into products (title, price, inventory_count) values ('Replacements, The', 69.58, 0);
insert into products (title, price, inventory_count) values ('Bass Ackwards', 59.04, 0);
insert into products (title, price, inventory_count) values ('¡Qué hacer!', 18.84, 892);
insert into products (title, price, inventory_count) values ('Instinct', 19.6, 751);
insert into products (title, price, inventory_count) values ('Cat and the Canary, The', 16.22, 0);
insert into products (title, price, inventory_count) values ('When Pigs Have Wings', 18.84, 184);
insert into products (title, price, inventory_count) values ('Watch on the Rhine', 38.04, 0);
insert into products (title, price, inventory_count) values ('Bride of Re-Animator', 29.53, 0);
insert into products (title, price, inventory_count) values ('Skylark', 41.96, 0);
insert into products (title, price, inventory_count) values ('Phantom Pain', 18.63, 356);
insert into products (title, price, inventory_count) values ('So Ends Our Night', 58.44, 0);
insert into products (title, price, inventory_count) values ('Rikyu', 35.0, 161);
insert into products (title, price, inventory_count) values ('Filth and Wisdom', 11.29, 651);
insert into products (title, price, inventory_count) values ('ID:A', 19.22, 700);
insert into products (title, price, inventory_count) values ('Monsters, Inc.', 62.05, 960);
insert into products (title, price, inventory_count) values ('Three Fugitives', 68.72, 0);
insert into products (title, price, inventory_count) values ('French Minister, The (Quai d''Orsay)', 68.45, 273);
insert into products (title, price, inventory_count) values ('Twin Sisters (De tweeling)', 39.81, 0);
insert into products (title, price, inventory_count) values ('Kingdom, The (Riget)', 50.17, 638);
insert into products (title, price, inventory_count) values ('[REC]²', 35.75, 318);
insert into products (title, price, inventory_count) values ('Belle Starr', 10.44, 543);
insert into products (title, price, inventory_count) values ('Casanova', 62.53, 0);
insert into products (title, price, inventory_count) values ('The Case of the Curious Bride', 30.89, 620);
insert into products (title, price, inventory_count) values ('Taking of Pelham 1 2 3, The', 14.76, 306);
insert into products (title, price, inventory_count) values ('Cheaper by the Dozen', 51.64, 694);
insert into products (title, price, inventory_count) values ('He Who Dares', 7.15, 326);
insert into products (title, price, inventory_count) values ('Bring It On', 48.44, 513);
insert into products (title, price, inventory_count) values ('Pushover', 12.23, 0);
insert into products (title, price, inventory_count) values ('Fools'' Parade', 50.57, 570);
insert into products (title, price, inventory_count) values ('Tyrannosaur', 16.89, 0);
insert into products (title, price, inventory_count) values ('Shark Attack', 43.41, 891);
insert into products (title, price, inventory_count) values ('Big Boss, The (Fists of Fury) (Tang shan da xiong)', 27.81, 666);
insert into products (title, price, inventory_count) values ('Personal Property', 29.06, 479);
insert into products (title, price, inventory_count) values ('Boot, Das (Boat, The)', 68.07, 701);
insert into products (title, price, inventory_count) values ('Side by Side', 29.72, 784);
insert into products (title, price, inventory_count) values ('Wayward Cloud, The (Tian bian yi duo yun)', 50.75, 496);
insert into products (title, price, inventory_count) values ('The Shooting', 39.83, 0);
insert into products (title, price, inventory_count) values ('Love Actually', 6.35, 0);
insert into products (title, price, inventory_count) values ('There''s Something Wrong with Aunt Diane', 57.48, 0);
insert into products (title, price, inventory_count) values ('Casper Meets Wendy', 46.04, 402);
insert into products (title, price, inventory_count) values ('Blob, The', 31.94, 271);
insert into products (title, price, inventory_count) values ('Godzilla vs. Mechagodzilla (Gojira tai Mekagojira)', 56.97, 571);
insert into products (title, price, inventory_count) values ('Ghost in the Machine (a.k.a. Deadly Terror)', 4.42, 0);
insert into products (title, price, inventory_count) values ('Outsiders (Ceddo)', 26.94, 0);
insert into products (title, price, inventory_count) values ('Divorce', 22.21, 732);
insert into products (title, price, inventory_count) values ('Kill Buljo: The Movie', 19.53, 653);
insert into products (title, price, inventory_count) values ('Young Doctors in Love', 41.85, 489);
insert into products (title, price, inventory_count) values ('Why Does Herr R. Run Amok? (Warum läuft Herr R. Amok?)', 52.16, 954);
insert into products (title, price, inventory_count) values ('Black Girl (La noire de...)', 32.42, 0);
insert into products (title, price, inventory_count) values ('Earthlings', 39.33, 962);
insert into products (title, price, inventory_count) values ('Track of the Cat', 47.67, 894);
insert into products (title, price, inventory_count) values ('Venus Boyz', 5.42, 704);
insert into products (title, price, inventory_count) values ('Episode 3: Enjoy Poverty', 23.29, 27);
insert into products (title, price, inventory_count) values ('Bossa Nova', 54.1, 0);
insert into products (title, price, inventory_count) values ('Gracie''s Choice', 27.39, 0);
insert into products (title, price, inventory_count) values ('Bonheur, Le', 51.94, 0);
insert into products (title, price, inventory_count) values ('Knights of Bloodsteel', 5.73, 0);
insert into products (title, price, inventory_count) values ('Monday Night Mayhem', 22.97, 591);
insert into products (title, price, inventory_count) values ('Good-bye, My Lady', 68.66, 0);
insert into products (title, price, inventory_count) values ('Beyond Justice', 26.18, 601);
insert into products (title, price, inventory_count) values ('Confessions of a Driving Instructor', 68.64, 0);
insert into products (title, price, inventory_count) values ('Beautiful Mind, A', 18.6, 892);
insert into products (title, price, inventory_count) values ('Kissing Jessica Stein', 58.94, 0);
insert into products (title, price, inventory_count) values ('Fantomas Unleashed', 57.65, 0);
insert into products (title, price, inventory_count) values ('My Girl 2', 21.05, 415);
insert into products (title, price, inventory_count) values ('House of Dracula', 36.83, 441);
insert into products (title, price, inventory_count) values ('Ivan Vasilievich: Back to the Future (Ivan Vasilievich menyaet professiyu)', 57.49, 296);
insert into products (title, price, inventory_count) values ('At Sea', 11.58, 171);
insert into products (title, price, inventory_count) values ('Brother (Hermano)', 8.13, 0);
insert into products (title, price, inventory_count) values ('Ponyo (Gake no ue no Ponyo)', 30.43, 0);
insert into products (title, price, inventory_count) values ('Stuart: A Life Backward', 24.07, 913);
insert into products (title, price, inventory_count) values ('Bill Cunningham New York', 53.27, 756);
insert into products (title, price, inventory_count) values ('The Death and Life of Bobby Z', 8.92, 680);
insert into products (title, price, inventory_count) values ('Simon Magus', 5.93, 335);
insert into products (title, price, inventory_count) values ('Airborne', 6.24, 0);
insert into products (title, price, inventory_count) values ('I''m Gonna Git You Sucka', 31.89, 771);
insert into products (title, price, inventory_count) values ('Paradox', 39.2, 0);
insert into products (title, price, inventory_count) values ('Freaky Deaky', 38.16, 347);
insert into products (title, price, inventory_count) values ('Fire Down Below', 8.28, 41);
insert into products (title, price, inventory_count) values ('Underworld', 28.72, 0);
insert into products (title, price, inventory_count) values ('I Love You, I Love You Not', 52.92, 920);
insert into products (title, price, inventory_count) values ('Still Life (Sanxia haoren)', 36.09, 0);
insert into products (title, price, inventory_count) values ('Earth', 60.45, 840);
insert into products (title, price, inventory_count) values ('Bullitt', 45.86, 133);
insert into products (title, price, inventory_count) values ('All I Want for Christmas', 9.85, 369);
insert into products (title, price, inventory_count) values ('Batman: Mystery of the Batwoman', 25.26, 0);
insert into products (title, price, inventory_count) values ('If You Could Only Cook', 7.33, 233);
insert into products (title, price, inventory_count) values ('Advise and Consent', 60.86, 403);
insert into products (title, price, inventory_count) values ('Butter', 19.33, 0);
insert into products (title, price, inventory_count) values ('Outbound (Periferic)', 14.98, 332);
insert into products (title, price, inventory_count) values ('Boys in the Band, The', 19.15, 378);
insert into products (title, price, inventory_count) values ('Don''t Tempt Me (Sin noticias de Dios)', 26.82, 936);
insert into products (title, price, inventory_count) values ('Charlie Chan in Paris', 62.12, 0);
insert into products (title, price, inventory_count) values ('Sea Inside, The (Mar adentro)', 35.65, 0);
insert into products (title, price, inventory_count) values ('Women Without Men (Zanan-e bedun-e mardan)', 20.37, 352);
insert into products (title, price, inventory_count) values ('Carny', 3.8, 166);
insert into products (title, price, inventory_count) values ('Can Go Through Skin (Kan door huid heen)', 35.33, 175);
insert into products (title, price, inventory_count) values ('American Carol, An', 39.0, 150);
insert into products (title, price, inventory_count) values ('My Joy (Schastye moe)', 9.19, 826);
insert into products (title, price, inventory_count) values ('Out-of-Towners, The', 26.2, 0);
insert into products (title, price, inventory_count) values ('What''s Up, Scarlet?', 26.79, 667);
insert into products (title, price, inventory_count) values ('Master of Disguise, The', 3.69, 376);
insert into products (title, price, inventory_count) values ('Righteous Kill', 41.1, 0);
insert into products (title, price, inventory_count) values ('Glass-blower''s Children, The (Glasblåsarns barn)', 31.0, 890);
insert into products (title, price, inventory_count) values ('Like Minds (Murderous Intent)', 41.75, 899);
insert into products (title, price, inventory_count) values ('Some Guy Who Kills People', 57.34, 0);
insert into products (title, price, inventory_count) values ('Ring, The', 15.82, 236);
insert into products (title, price, inventory_count) values ('Steam Experiment, The', 61.8, 838);
insert into products (title, price, inventory_count) values ('Welcome to the Rileys', 42.11, 969);
insert into products (title, price, inventory_count) values ('Santa Claus', 39.92, 307);
insert into products (title, price, inventory_count) values ('Under African Skies', 27.49, 0);
insert into products (title, price, inventory_count) values ('Paziraie Sadeh', 52.11, 0);
insert into products (title, price, inventory_count) values ('Waiting Women (Kvinnors väntan)', 45.72, 661);
insert into products (title, price, inventory_count) values ('Incident at Oglala', 14.04, 438);
insert into products (title, price, inventory_count) values ('Nothing But the Night', 10.9, 0);
insert into products (title, price, inventory_count) values ('Male and Female', 27.46, 0);
insert into products (title, price, inventory_count) values ('Treacle Jr.', 65.5, 171);
insert into products (title, price, inventory_count) values ('Affair of the Necklace, The', 53.59, 455);
insert into products (title, price, inventory_count) values ('Steep', 52.41, 15);
insert into products (title, price, inventory_count) values ('What Price Glory', 65.47, 479);
insert into products (title, price, inventory_count) values ('Tapia', 46.6, 71);
insert into products (title, price, inventory_count) values ('Street Mobster (a.k.a. Modern Yakuza: Outlaw Killer) (Gendai yakuza: hito-kiri yota)', 33.69, 866);
insert into products (title, price, inventory_count) values ('Graduate, The', 62.97, 0);
insert into products (title, price, inventory_count) values ('Substitute, The (Vikaren)', 56.41, 618);
insert into products (title, price, inventory_count) values ('Seitsemän veljestä', 57.82, 541);
insert into products (title, price, inventory_count) values ('Pit and the Pendulum, The', 21.23, 152);
insert into products (title, price, inventory_count) values ('Inspector Bellamy (Bellamy)', 38.21, 971);
insert into products (title, price, inventory_count) values ('Lore', 14.15, 25);
insert into products (title, price, inventory_count) values ('Tyler Perry''s Why Did I Get Married Too?', 56.22, 623);
insert into products (title, price, inventory_count) values ('Into the Sun', 45.58, 0);
insert into products (title, price, inventory_count) values ('Way, Way Back, The', 25.84, 894);
insert into products (title, price, inventory_count) values ('Legend of Suram Fortress, The (Ambavi Suramis tsikhitsa) ', 28.84, 358);
insert into products (title, price, inventory_count) values ('Tenderness', 36.11, 950);
insert into products (title, price, inventory_count) values ('Behind the Screen', 18.96, 64);
insert into products (title, price, inventory_count) values ('Man of the East', 25.79, 576);
insert into products (title, price, inventory_count) values ('Wanted: Dead or Alive', 44.0, 915);
insert into products (title, price, inventory_count) values ('Remember the Titans', 60.83, 353);
insert into products (title, price, inventory_count) values ('Sunset Park', 7.64, 541);
insert into products (title, price, inventory_count) values ('French Cancan', 11.63, 557);
insert into products (title, price, inventory_count) values ('Sentinel, The', 68.46, 0);
insert into products (title, price, inventory_count) values ('The Thirteen Assassins', 45.03, 538);
insert into products (title, price, inventory_count) values ('Show People', 18.34, 0);
insert into products (title, price, inventory_count) values ('Kinsey', 60.56, 704);
insert into products (title, price, inventory_count) values ('What the #$*! Do We Know!? (a.k.a. What the Bleep Do We Know!?)', 23.54, 729);
insert into products (title, price, inventory_count) values ('Pleasures of the Flesh (Etsuraku)', 26.79, 0);
insert into products (title, price, inventory_count) values ('Three Men and a Cradle (3 hommes et un couffin)', 60.76, 573);
insert into products (title, price, inventory_count) values ('Misfits, The', 47.37, 715);
insert into products (title, price, inventory_count) values ('Fallen Sparrow, The', 34.39, 516);
insert into products (title, price, inventory_count) values ('Dancing in September', 64.68, 486);
insert into products (title, price, inventory_count) values ('Bhutto', 36.51, 0);
insert into products (title, price, inventory_count) values ('Eye of the Devil', 35.9, 95);
insert into products (title, price, inventory_count) values ('i hate myself :)', 14.1, 0);
insert into products (title, price, inventory_count) values ('Fade to Black', 33.39, 865);
insert into products (title, price, inventory_count) values ('The Bone Snatcher', 63.1, 977);
insert into products (title, price, inventory_count) values ('How High', 40.35, 0);
insert into products (title, price, inventory_count) values ('Dances Sacred and Profane', 13.24, 0);
insert into products (title, price, inventory_count) values ('Tonight You''re Mine', 14.34, 595);
insert into products (title, price, inventory_count) values ('Religulous', 16.55, 0);
insert into products (title, price, inventory_count) values ('Summer Days With Coo', 56.0, 745);
insert into products (title, price, inventory_count) values ('Power Play', 17.72, 590);
insert into products (title, price, inventory_count) values ('Steal a Pencil for Me', 37.47, 835);
insert into products (title, price, inventory_count) values ('Bad Taste', 36.58, 264);
insert into products (title, price, inventory_count) values ('Square Dance', 50.75, 0);
insert into products (title, price, inventory_count) values ('Wrinkles (Arrugas)', 33.24, 0);
insert into products (title, price, inventory_count) values ('Slumming', 11.04, 290);
insert into products (title, price, inventory_count) values ('Across the Line: The Exodus of Charlie Wright', 9.91, 246);
insert into products (title, price, inventory_count) values ('Darling', 38.3, 0);
insert into products (title, price, inventory_count) values ('Kill Me Now', 30.02, 940);
insert into products (title, price, inventory_count) values ('That Thing You Do!', 42.45, 965);
insert into products (title, price, inventory_count) values ('Liam', 39.41, 757);
insert into products (title, price, inventory_count) values ('Half Past Dead', 31.74, 484);
insert into products (title, price, inventory_count) values ('Audition (Konkurs)', 3.29, 220);
insert into products (title, price, inventory_count) values ('Tears of April (Käsky)', 9.72, 528);
insert into products (title, price, inventory_count) values ('Blue Hawaii', 64.13, 341);
insert into products (title, price, inventory_count) values ('Misérables, Les', 36.45, 922);
insert into products (title, price, inventory_count) values ('Yamla Pagla Deewana 2', 67.23, 0);
insert into products (title, price, inventory_count) values ('Jade', 15.21, 446);
insert into products (title, price, inventory_count) values ('Chicago', 54.1, 409);
insert into products (title, price, inventory_count) values ('Oliver Twist', 11.2, 0);
insert into products (title, price, inventory_count) values ('Medicine for Melancholy', 35.54, 493);
insert into products (title, price, inventory_count) values ('Jaws 2', 59.61, 47);
insert into products (title, price, inventory_count) values ('Buster Keaton: A Hard Act to Follow', 42.69, 0);
insert into products (title, price, inventory_count) values ('No Nukes', 48.07, 358);
insert into products (title, price, inventory_count) values ('We Always Lie to Strangers', 51.93, 555);
insert into products (title, price, inventory_count) values ('Sleepover', 28.78, 0);
insert into products (title, price, inventory_count) values ('Dylan Moran Live: What It Is', 39.06, 834);
insert into products (title, price, inventory_count) values ('American Pie', 21.37, 566);
insert into products (title, price, inventory_count) values ('Martha', 50.33, 888);
insert into products (title, price, inventory_count) values ('Can''t Buy Me Love', 69.42, 609);
insert into products (title, price, inventory_count) values ('Last Chance Harvey', 59.65, 53);
insert into products (title, price, inventory_count) values ('Brother, Can You Spare a Dime?', 64.57, 665);
insert into products (title, price, inventory_count) values ('House on Haunted Hill', 7.18, 4);
insert into products (title, price, inventory_count) values ('Polish Wedding', 4.72, 261);
insert into products (title, price, inventory_count) values ('Head', 61.38, 673);
insert into products (title, price, inventory_count) values ('Merry Widow, The', 61.26, 330);
insert into products (title, price, inventory_count) values ('Little Black Book', 32.56, 0);
insert into products (title, price, inventory_count) values ('Igor', 42.79, 0);
insert into products (title, price, inventory_count) values ('Shadrach', 3.47, 957);
insert into products (title, price, inventory_count) values ('Rocky Balboa', 46.46, 956);
insert into products (title, price, inventory_count) values ('Brooklyn', 20.11, 915);
insert into products (title, price, inventory_count) values ('Miracle Woman, The', 14.09, 0);
insert into products (title, price, inventory_count) values ('The Care Bears Adventure in Wonderland', 18.94, 0);
insert into products (title, price, inventory_count) values ('Mississippi Burning', 65.14, 0);
insert into products (title, price, inventory_count) values ('Free the Nipple', 53.43, 84);
insert into products (title, price, inventory_count) values ('Pear Tree, The (Derakhte Golabi)', 10.59, 13);
insert into products (title, price, inventory_count) values ('Career Girls', 49.48, 0);
insert into products (title, price, inventory_count) values ('Castle Keep', 3.91, 723);
insert into products (title, price, inventory_count) values ('Dragonfly', 46.37, 0);
insert into products (title, price, inventory_count) values ('Broadway Bill', 69.89, 719);
insert into products (title, price, inventory_count) values ('Style Wars', 43.26, 961);
insert into products (title, price, inventory_count) values ('10 Things I Hate About You', 14.23, 588);
insert into products (title, price, inventory_count) values ('Vai~E~Vem', 36.62, 749);
insert into products (title, price, inventory_count) values ('Queen, The', 14.07, 138);
insert into products (title, price, inventory_count) values ('Kathleen', 43.59, 0);
insert into products (title, price, inventory_count) values ('Halloween', 29.04, 332);
insert into products (title, price, inventory_count) values ('Hope and Glory', 42.8, 320);
insert into products (title, price, inventory_count) values ('Small Soldiers', 63.77, 435);
insert into products (title, price, inventory_count) values ('Jack the Giant Slayer', 52.47, 812);
insert into products (title, price, inventory_count) values ('Not as a Stranger', 33.32, 984);
insert into products (title, price, inventory_count) values ('Dragon Ball Z: Bojack Unbound (Doragon bôru Z 9: Ginga girigiri!! Butchigiri no sugoi yatsu)', 24.37, 0);
insert into products (title, price, inventory_count) values ('Marjoe', 44.24, 0);
insert into products (title, price, inventory_count) values ('Hachiko: A Dog''s Story (a.k.a. Hachi: A Dog''s Tale)', 7.91, 0);
insert into products (title, price, inventory_count) values ('All In: The Poker Movie', 40.32, 751);
insert into products (title, price, inventory_count) values ('Lady in the Lake', 61.64, 0);
insert into products (title, price, inventory_count) values ('Romper Stomper', 28.97, 621);
insert into products (title, price, inventory_count) values ('18 Again!', 22.83, 0);
insert into products (title, price, inventory_count) values ('Not Easily Broken', 37.92, 236);
insert into products (title, price, inventory_count) values ('Cannonball', 65.75, 670);
insert into products (title, price, inventory_count) values ('Cialo', 10.36, 235);
insert into products (title, price, inventory_count) values ('Pudana Last of the Line (Sukunsa viimeinen)', 27.18, 199);
insert into products (title, price, inventory_count) values ('How the Grinch Stole Christmas!', 19.11, 200);
insert into products (title, price, inventory_count) values ('Wetherby', 16.24, 0);
insert into products (title, price, inventory_count) values ('Angélique, marquise des anges', 5.12, 656);
insert into products (title, price, inventory_count) values ('Love''s Long Journey', 52.68, 853);
insert into products (title, price, inventory_count) values ('My Chauffeur', 14.11, 0);
insert into products (title, price, inventory_count) values ('Union, The', 18.21, 609);
insert into products (title, price, inventory_count) values ('Kid Galahad', 37.35, 912);
insert into products (title, price, inventory_count) values ('Forest of the Gods (Dievu miskas)', 44.81, 0);
insert into products (title, price, inventory_count) values ('Afternoon Delight', 19.79, 0);
insert into products (title, price, inventory_count) values ('The Tenant of Wildfell Hall', 9.68, 0);
insert into products (title, price, inventory_count) values ('Man - Woman Wanted (Poszukiwany, poszukiwana)', 47.29, 373);
insert into products (title, price, inventory_count) values ('Outrage', 58.02, 308);
insert into products (title, price, inventory_count) values ('Pont du Nord, Le', 68.72, 188);
insert into products (title, price, inventory_count) values ('Hawks and Sparrows (Uccellacci e Uccellini)', 37.48, 371);
insert into products (title, price, inventory_count) values ('You Got Served', 51.25, 0);
insert into products (title, price, inventory_count) values ('About Elly (Darbareye Elly)', 5.53, 140);
insert into products (title, price, inventory_count) values ('Invasion of the Bee Girls', 63.55, 414);
insert into products (title, price, inventory_count) values ('Who the #$&% is Jackson Pollock?', 69.23, 0);
insert into products (title, price, inventory_count) values ('Hider in the House', 13.43, 559);
insert into products (title, price, inventory_count) values ('Deep End', 59.83, 0);
insert into products (title, price, inventory_count) values ('Murder on a Honeymoon', 6.51, 58);
insert into products (title, price, inventory_count) values ('Restoration', 69.09, 501);
insert into products (title, price, inventory_count) values ('Wedding Photographer, The (Bröllopsfotografen)', 36.23, 764);
insert into products (title, price, inventory_count) values ('Blaise Pascal', 46.0, 408);
insert into products (title, price, inventory_count) values ('Reign of Fire', 19.36, 614);
insert into products (title, price, inventory_count) values ('King of Ping Pong, The (Ping-pongkingen)', 42.64, 685);
insert into products (title, price, inventory_count) values ('Christmas Carol, A', 67.12, 0);
insert into products (title, price, inventory_count) values ('Crew, The', 67.7, 154);
insert into products (title, price, inventory_count) values ('Scribbler, The', 34.26, 710);
insert into products (title, price, inventory_count) values ('Fall Time', 8.23, 0);
insert into products (title, price, inventory_count) values ('Bears', 45.27, 842);
insert into products (title, price, inventory_count) values ('Tupac: Resurrection', 44.7, 813);
insert into products (title, price, inventory_count) values ('Beauty of the Day (Belle de jour)', 69.91, 85);
insert into products (title, price, inventory_count) values ('Mole People, The', 28.26, 586);
insert into products (title, price, inventory_count) values ('Dhoondte Reh Jaoge', 67.25, 593);
insert into products (title, price, inventory_count) values ('Hudson Hawk', 43.42, 720);
insert into products (title, price, inventory_count) values ('Monster X Strikes Back: Attack the G8 Summit, The (Girara no gyakushû: Tôya-ko Samitto kikiippatsu)', 7.54, 690);
insert into products (title, price, inventory_count) values ('Street Trash', 38.45, 0);
insert into products (title, price, inventory_count) values ('Sherlock Holmes: A Game of Shadows', 39.28, 187);
insert into products (title, price, inventory_count) values ('Trespass', 49.44, 813);
insert into products (title, price, inventory_count) values ('Cold Creek Manor', 41.79, 527);
insert into products (title, price, inventory_count) values ('Bat, The', 16.78, 545);
insert into products (title, price, inventory_count) values ('Final Darkness, The (Buio Omega)', 6.43, 608);
insert into products (title, price, inventory_count) values ('Zerophilia', 3.1, 250);
insert into products (title, price, inventory_count) values ('Life Is What You Make It (Linha de Passe)', 10.57, 840);
insert into products (title, price, inventory_count) values ('What Price Hollywood?', 59.14, 174);
insert into products (title, price, inventory_count) values ('Creep', 53.97, 0);
insert into products (title, price, inventory_count) values ('Looker', 61.76, 932);
insert into products (title, price, inventory_count) values ('Mildred Pierce', 35.75, 170);
insert into products (title, price, inventory_count) values ('Point Blank', 14.85, 85);
insert into products (title, price, inventory_count) values ('Hand That Rocks the Cradle, The', 40.24, 79);
insert into products (title, price, inventory_count) values ('Red Spectacles, The (Jigoku no banken: akai megane)', 49.9, 652);
insert into products (title, price, inventory_count) values ('The Shoe', 23.13, 696);
insert into products (title, price, inventory_count) values ('Hell to Eternity', 25.32, 0);
insert into products (title, price, inventory_count) values ('Jaws', 19.89, 170);
insert into products (title, price, inventory_count) values ('Chairman of the Board', 53.62, 97);
insert into products (title, price, inventory_count) values ('War of the Arrows (Choi-jong-byeong-gi Hwal)', 12.89, 0);
insert into products (title, price, inventory_count) values ('No Greater Love', 37.28, 987);
insert into products (title, price, inventory_count) values ('The Killing Jar', 18.73, 568);
insert into products (title, price, inventory_count) values ('Closer You Get, The', 21.13, 161);
insert into products (title, price, inventory_count) values ('Step Up', 40.65, 637);
insert into products (title, price, inventory_count) values ('Humboldt County', 52.71, 486);
insert into products (title, price, inventory_count) values ('¡Qué hacer!', 36.4, 128);
insert into products (title, price, inventory_count) values ('Sniper 2', 13.79, 0);
insert into products (title, price, inventory_count) values ('Elegy', 58.09, 5);
insert into products (title, price, inventory_count) values ('Peggy Sue Got Married', 50.6, 0);
insert into products (title, price, inventory_count) values ('Ex, The', 23.47, 0);
insert into products (title, price, inventory_count) values ('Rampage at Apache Wells', 44.79, 363);
insert into products (title, price, inventory_count) values ('Invaders from Mars', 36.59, 126);
insert into products (title, price, inventory_count) values ('Drogówka', 13.86, 42);
insert into products (title, price, inventory_count) values ('Enlightenment Guaranteed (Erleuchtung Garantiert)', 33.18, 187);
insert into products (title, price, inventory_count) values ('Unstrung Heroes', 16.66, 0);
insert into products (title, price, inventory_count) values ('Ichi', 8.22, 264);
insert into products (title, price, inventory_count) values ('Miss You Can Do It', 27.74, 995);
insert into products (title, price, inventory_count) values ('Punk''s Dead: SLC Punk! 2', 14.95, 0);
insert into products (title, price, inventory_count) values ('Year Zero: The Silent Death of Cambodia', 27.22, 0);
insert into products (title, price, inventory_count) values ('Tortured', 43.39, 395);
insert into products (title, price, inventory_count) values ('Faster Pussycat! Kill! Kill!', 55.22, 0);
insert into products (title, price, inventory_count) values ('Kurt Cobain: Montage of Heck', 33.54, 499);
insert into products (title, price, inventory_count) values ('On the Ice', 12.07, 0);
insert into products (title, price, inventory_count) values ('The Forgotten Woman', 9.23, 31);
insert into products (title, price, inventory_count) values ('Annie', 7.95, 901);
insert into products (title, price, inventory_count) values ('Wizard, The', 29.5, 644);
insert into products (title, price, inventory_count) values ('Tao of Steve, The', 66.17, 645);
insert into products (title, price, inventory_count) values ('Run Ronnie Run', 44.27, 502);
insert into products (title, price, inventory_count) values ('Wizard of Oz, The', 39.6, 677);
insert into products (title, price, inventory_count) values ('Wild Wild West', 54.64, 385);
insert into products (title, price, inventory_count) values ('Escape from Planet Earth', 15.71, 591);
insert into products (title, price, inventory_count) values ('My Wife, A Body to Love', 31.65, 471);
insert into products (title, price, inventory_count) values ('Story of the Late Chrysanthemums, The (Zangiku monogatari)', 41.97, 297);
insert into products (title, price, inventory_count) values ('Carry On, Constable', 66.33, 0);
insert into products (title, price, inventory_count) values ('White Heat', 6.77, 939);
insert into products (title, price, inventory_count) values ('Mortal Instruments: City of Bones, The', 58.28, 954);
insert into products (title, price, inventory_count) values ('The Horseplayer', 53.42, 102);
insert into products (title, price, inventory_count) values ('Fed Up', 30.46, 0);
insert into products (title, price, inventory_count) values ('Driving Lessons', 44.07, 324);
insert into products (title, price, inventory_count) values ('Basic Instinct 2', 33.3, 158);
insert into products (title, price, inventory_count) values ('Casualties of War', 44.76, 0);
insert into products (title, price, inventory_count) values ('Cool It', 13.46, 876);
insert into products (title, price, inventory_count) values ('Tyler Perry''s Madea''s Family Reunion', 33.39, 0);
insert into products (title, price, inventory_count) values ('In Therapy (Divã)', 9.24, 203);
insert into products (title, price, inventory_count) values ('Tortoise and the Hare, The', 41.88, 0);
insert into products (title, price, inventory_count) values ('Friend of Mine, A (Ein Freund von mir)', 67.44, 201);
insert into products (title, price, inventory_count) values ('Charlie Chan''s Greatest Case', 60.51, 0);
insert into products (title, price, inventory_count) values ('Into the Blue 2: The Reef', 40.51, 699);
insert into products (title, price, inventory_count) values ('Saving Santa', 27.95, 0);
insert into products (title, price, inventory_count) values ('Kiss Before Dying, A', 36.16, 446);
insert into products (title, price, inventory_count) values ('Stricken (Er komt een vrouw bij de dokter)', 40.47, 432);
insert into products (title, price, inventory_count) values ('5 Days of War', 33.82, 553);
insert into products (title, price, inventory_count) values ('Something Like Happiness (Stestí)', 36.9, 310);
insert into products (title, price, inventory_count) values ('Way of the Gun, The', 21.14, 819);
insert into products (title, price, inventory_count) values ('Seven Brides for Seven Brothers', 4.23, 0);
insert into products (title, price, inventory_count) values ('Curb Dance', 9.01, 418);
insert into products (title, price, inventory_count) values ('Mostly Unfabulous Social Life of Ethan Green, The', 11.64, 0);
insert into products (title, price, inventory_count) values ('Adios Sabata', 38.56, 505);
insert into products (title, price, inventory_count) values ('Africa addio', 11.0, 0);
insert into products (title, price, inventory_count) values ('Toxic Avenger, Part II, The', 57.37, 897);
insert into products (title, price, inventory_count) values ('Vehicle 19', 8.25, 589);
insert into products (title, price, inventory_count) values ('Innkeepers, The', 39.14, 419);
insert into products (title, price, inventory_count) values ('Shrek 2', 54.26, 214);
insert into products (title, price, inventory_count) values ('Mummy: Tomb of the Dragon Emperor, The', 6.51, 0);
insert into products (title, price, inventory_count) values ('Sailor of the King', 60.57, 0);
insert into products (title, price, inventory_count) values ('Louise Bourgeois: The Spider, the Mistress and the Tangerine', 3.34, 425);
insert into products (title, price, inventory_count) values ('Best Little Whorehouse in Texas, The', 7.41, 95);
insert into products (title, price, inventory_count) values ('Kill, Baby, Kill (Operazione paura)', 68.27, 451);
insert into products (title, price, inventory_count) values ('Statues Also Die (Statues meurent aussi, Les)', 15.29, 994);
insert into products (title, price, inventory_count) values ('Max Payne', 23.57, 837);
insert into products (title, price, inventory_count) values ('Mystery of the 13th Guest', 47.67, 956);
insert into products (title, price, inventory_count) values ('Larger Than Life', 45.48, 0);
insert into products (title, price, inventory_count) values ('House IV', 24.3, 153);
insert into products (title, price, inventory_count) values ('Walt & El Grupo', 16.46, 565);
insert into products (title, price, inventory_count) values ('Planet of the Apes', 12.15, 0);
insert into products (title, price, inventory_count) values ('Hard Day''s Night, A', 7.15, 0);
insert into products (title, price, inventory_count) values ('House Is Black, The', 54.03, 30);
insert into products (title, price, inventory_count) values ('April Showers', 64.37, 190);
insert into products (title, price, inventory_count) values ('Startup.com', 26.79, 125);
insert into products (title, price, inventory_count) values ('Curious George', 32.81, 541);
insert into products (title, price, inventory_count) values ('Laughing Policeman, The', 48.61, 550);
insert into products (title, price, inventory_count) values ('Eight Men Out', 68.55, 871);
insert into products (title, price, inventory_count) values ('Lotte Reiniger: Homage to the Inventor of the Silhouette Film', 51.07, 0);
insert into products (title, price, inventory_count) values ('Murder Party', 46.58, 823);
insert into products (title, price, inventory_count) values ('Gracie''s Choice', 50.59, 0);
insert into products (title, price, inventory_count) values ('Wake', 12.53, 152);
insert into products (title, price, inventory_count) values ('The Secret Country: The First Australians Fight Back', 66.59, 242);
insert into products (title, price, inventory_count) values ('August (Elokuu) ', 31.69, 448);
insert into products (title, price, inventory_count) values ('Rush', 29.5, 0);
insert into products (title, price, inventory_count) values ('Heart Is Deceitful Above All Things, The', 33.09, 0);
insert into products (title, price, inventory_count) values ('Blast', 21.8, 485);
insert into products (title, price, inventory_count) values ('Guinea Pig: Flowers of Flesh and Blood (Za ginipiggu 2: Chiniku no hana)', 5.27, 199);
insert into products (title, price, inventory_count) values ('Kurt Cobain: Montage of Heck', 34.04, 46);
insert into products (title, price, inventory_count) values ('Little Bit of Heaven, A', 55.35, 427);
insert into products (title, price, inventory_count) values ('Firestorm', 17.62, 924);
insert into products (title, price, inventory_count) values ('Kiss and Make-Up', 3.78, 790);
insert into products (title, price, inventory_count) values ('America the Beautiful 2: The Thin Commandments ', 52.68, 212);
insert into products (title, price, inventory_count) values ('Juno', 66.19, 637);
insert into products (title, price, inventory_count) values ('National Gallery', 69.96, 656);
insert into products (title, price, inventory_count) values ('Boy Called Hate, A', 25.82, 739);
insert into products (title, price, inventory_count) values ('Wild China', 22.57, 223);
insert into products (title, price, inventory_count) values ('Dealing: Or the Berkeley-to-Boston Forty-Brick Lost-Bag Blues', 44.71, 901);
insert into products (title, price, inventory_count) values ('Samurai Banners (Fûrin kazan)', 54.28, 772);
insert into products (title, price, inventory_count) values ('Always', 51.07, 455);
insert into products (title, price, inventory_count) values ('For the Love of Benji', 10.25, 94);
insert into products (title, price, inventory_count) values ('Barbarian Queen II: The Empress Strikes Back', 35.04, 359);
insert into products (title, price, inventory_count) values ('Babylon', 11.75, 793);
insert into products (title, price, inventory_count) values ('Andromeda Strain, The', 53.86, 109);
insert into products (title, price, inventory_count) values ('Rage: Carrie 2, The', 28.47, 0);
insert into products (title, price, inventory_count) values ('Save the Tiger', 34.96, 0);
insert into products (title, price, inventory_count) values ('New Scenes from America', 30.05, 884);
insert into products (title, price, inventory_count) values ('Tai-Pan', 36.54, 361);
insert into products (title, price, inventory_count) values ('Riding in Cars with Boys', 55.63, 0);
insert into products (title, price, inventory_count) values ('Airborne', 61.66, 742);
insert into products (title, price, inventory_count) values ('Last Seven, The', 68.18, 0);
insert into products (title, price, inventory_count) values ('Sky Captain and the World of Tomorrow', 63.18, 114);
insert into products (title, price, inventory_count) values ('Major League II', 65.2, 914);
insert into products (title, price, inventory_count) values ('Walking with Monsters', 60.53, 592);
insert into products (title, price, inventory_count) values ('Quiet, The', 56.97, 69);
insert into products (title, price, inventory_count) values ('Sharpe''s Eagle', 28.24, 0);
insert into products (title, price, inventory_count) values ('Spider''s Stratagem, The (Strategia del ragno)', 48.91, 62);
insert into products (title, price, inventory_count) values ('Sleuth', 25.49, 0);
insert into products (title, price, inventory_count) values ('Disorder', 65.08, 561);
insert into products (title, price, inventory_count) values ('Angel', 11.19, 0);
insert into products (title, price, inventory_count) values ('Poseidon', 27.94, 964);
insert into products (title, price, inventory_count) values ('Jeanne Dielman, 23 Quai du Commerce, 1080 Bruxelles', 66.52, 800);
insert into products (title, price, inventory_count) values ('Code Name: The Cleaner', 50.14, 0);
insert into products (title, price, inventory_count) values ('Savannah', 4.95, 0);
insert into products (title, price, inventory_count) values ('Caligula', 65.58, 0);
insert into products (title, price, inventory_count) values ('Home of the Brave', 37.63, 626);
insert into products (title, price, inventory_count) values ('Crimson Rivers 2: Angels of the Apocalypse (Rivières pourpres II - Les anges de l''apocalypse, Les)', 12.3, 0);
insert into products (title, price, inventory_count) values ('Blackrock', 36.67, 368);
insert into products (title, price, inventory_count) values ('Night of the Hunter, The', 11.43, 0);
insert into products (title, price, inventory_count) values ('French Film', 21.55, 0);
insert into products (title, price, inventory_count) values ('Case for Christ, The', 40.54, 0);
insert into products (title, price, inventory_count) values ('Petits ruisseaux, Les', 55.1, 378);
insert into products (title, price, inventory_count) values ('Season''s Greetings', 12.93, 519);
insert into products (title, price, inventory_count) values ('Rat Race, The (Garson Kanin''s The Rat Race)', 42.35, 114);
insert into products (title, price, inventory_count) values ('Disco and Atomic War (Disko ja tuumasõda)', 12.3, 785);
insert into products (title, price, inventory_count) values ('Telefon', 35.69, 0);
insert into products (title, price, inventory_count) values ('Septième juré, Le', 18.75, 551);
insert into products (title, price, inventory_count) values ('Breaking the Maya Code', 63.93, 526);
insert into products (title, price, inventory_count) values ('Graduation Day', 16.21, 613);
insert into products (title, price, inventory_count) values ('Berlin Babylon', 53.48, 0);
insert into products (title, price, inventory_count) values ('Miranda', 62.94, 250);
insert into products (title, price, inventory_count) values ('Each Dawn I Die', 17.92, 302);
insert into products (title, price, inventory_count) values ('Jet Li''s Fearless (Huo Yuan Jia)', 67.25, 0);
insert into products (title, price, inventory_count) values ('Creation of the Humanoids, The', 47.87, 331);
insert into products (title, price, inventory_count) values ('Ain''t in It for My Health: A Film About Levon Helm', 52.86, 297);
insert into products (title, price, inventory_count) values ('At Close Range', 42.41, 861);
insert into products (title, price, inventory_count) values ('Deadline', 30.5, 0);
insert into products (title, price, inventory_count) values ('Berlin Express', 34.79, 75);
insert into products (title, price, inventory_count) values ('Red Hill', 7.28, 248);
insert into products (title, price, inventory_count) values ('Osterman Weekend, The', 57.57, 682);
insert into products (title, price, inventory_count) values ('The Boy Who Cried Werewolf', 55.15, 423);
insert into products (title, price, inventory_count) values ('Night at the Museum: Battle of the Smithsonian', 37.15, 0);
insert into products (title, price, inventory_count) values ('Bodyguards and Assassins', 53.8, 79);
insert into products (title, price, inventory_count) values ('The Concert for Bangladesh', 51.81, 0);
insert into products (title, price, inventory_count) values ('Children of Huang Shi, The', 62.84, 327);
insert into products (title, price, inventory_count) values ('Cry Freedom', 68.4, 432);
insert into products (title, price, inventory_count) values ('Ride Along', 32.67, 0);
insert into products (title, price, inventory_count) values ('Girl of Your Dreams, The (Niña de tus ojos, La)', 7.89, 41);
insert into products (title, price, inventory_count) values ('Comme un chef', 63.93, 485);
insert into products (title, price, inventory_count) values ('Tension at Table Rock', 14.65, 0);
insert into products (title, price, inventory_count) values ('Alone for Christmas', 19.43, 220);
insert into products (title, price, inventory_count) values ('Nazareno Cruz and the Wolf', 10.85, 878);
insert into products (title, price, inventory_count) values ('Loners (Samotári)', 39.52, 186);
insert into products (title, price, inventory_count) values ('Lady Sings the Blues', 51.13, 0);
insert into products (title, price, inventory_count) values ('Suicide Manual (Jisatsu manyaru)', 27.91, 904);
insert into products (title, price, inventory_count) values ('Dirigible', 21.9, 514);
insert into products (title, price, inventory_count) values ('Point of No Return', 61.69, 0);
insert into products (title, price, inventory_count) values ('Tromeo and Juliet', 56.04, 0);
insert into products (title, price, inventory_count) values ('The Hire: Ticker', 17.18, 316);
insert into products (title, price, inventory_count) values ('Sky West and Crooked (Gypsy Girl)', 54.44, 0);
insert into products (title, price, inventory_count) values ('Fire and Ice', 51.59, 0);
insert into products (title, price, inventory_count) values ('Diamonds Are Forever', 3.63, 428);
insert into products (title, price, inventory_count) values ('Missing Person, The', 7.39, 0);
insert into products (title, price, inventory_count) values ('The Appointments of Dennis Jennings', 46.6, 0);
insert into products (title, price, inventory_count) values ('3 Bad Men', 20.27, 221);
insert into products (title, price, inventory_count) values ('Man in the Glass Booth, The', 52.23, 0);
insert into products (title, price, inventory_count) values ('Double Life, A', 19.63, 701);
insert into products (title, price, inventory_count) values ('Santa Who?', 5.44, 511);
insert into products (title, price, inventory_count) values ('Day He Arrives, The (Book chon bang hyang)', 61.44, 300);
insert into products (title, price, inventory_count) values ('Getting In', 50.41, 960);
insert into products (title, price, inventory_count) values ('Ten Inch Hero', 27.07, 262);
insert into products (title, price, inventory_count) values ('Pariah', 42.69, 275);
insert into products (title, price, inventory_count) values ('Nightmare', 66.65, 0);
insert into products (title, price, inventory_count) values ('Snow White (Blancanieves)', 10.55, 251);
insert into products (title, price, inventory_count) values ('Woman Who Drinks, The (La femme qui boit)', 25.46, 837);
insert into products (title, price, inventory_count) values ('Bloodfist', 28.65, 258);
insert into products (title, price, inventory_count) values ('Under African Skies', 53.67, 770);
insert into products (title, price, inventory_count) values ('Tenacious D in The Pick of Destiny', 24.13, 361);
insert into products (title, price, inventory_count) values ('Ski Patrol', 27.11, 0);
insert into products (title, price, inventory_count) values ('Taken', 8.34, 3);
insert into products (title, price, inventory_count) values ('Crossworlds', 64.21, 548);
insert into products (title, price, inventory_count) values ('Outrageous Fortune', 58.72, 0);
insert into products (title, price, inventory_count) values ('Planes', 34.4, 0);
insert into products (title, price, inventory_count) values ('Page of Madness, A (Kurutta ippêji)', 30.06, 260);
insert into products (title, price, inventory_count) values ('Vamps', 13.72, 494);
insert into products (title, price, inventory_count) values ('Civic Duty', 52.35, 906);
insert into products (title, price, inventory_count) values ('Not Another Teen Movie', 46.35, 0);
insert into products (title, price, inventory_count) values ('Blueberry', 18.52, 871);
insert into products (title, price, inventory_count) values ('Crazy Beautiful You', 68.07, 801);
insert into products (title, price, inventory_count) values ('Just Friends?', 12.29, 783);
insert into products (title, price, inventory_count) values ('Deep, The (Djúpið)', 10.9, 0);
insert into products (title, price, inventory_count) values ('Rentun Ruusu', 14.63, 217);
insert into products (title, price, inventory_count) values ('Hiding Cot (Piilopirtti)', 45.43, 286);
insert into products (title, price, inventory_count) values ('Taking Off', 3.58, 607);
insert into products (title, price, inventory_count) values ('I Bought a Vampire Motorcycle', 26.62, 0);
insert into products (title, price, inventory_count) values ('Monty Python Live (Mostly)', 61.31, 598);
insert into products (title, price, inventory_count) values ('Our Fathers', 52.22, 407);
insert into products (title, price, inventory_count) values ('Evan Almighty', 49.81, 965);
insert into products (title, price, inventory_count) values ('Detroit', 19.53, 0);
insert into products (title, price, inventory_count) values ('Asterix & Obelix: Mission Cleopatra (Astérix & Obélix: Mission Cléopâtre)', 29.57, 552);
insert into products (title, price, inventory_count) values ('Reluctant Fundamentalist, The', 18.33, 68);
insert into products (title, price, inventory_count) values ('Season for Miracles, A', 4.83, 0);
insert into products (title, price, inventory_count) values ('Juwanna Mann', 66.64, 405);
insert into products (title, price, inventory_count) values ('Cool Air', 5.28, 0);
insert into products (title, price, inventory_count) values ('Rare Birds', 50.6, 64);
insert into products (title, price, inventory_count) values ('41-Year-Old Virgin Who Knocked Up Sarah Marshall and Felt Superbad About It, The', 67.91, 692);
insert into products (title, price, inventory_count) values ('Something of Value', 16.86, 896);
insert into products (title, price, inventory_count) values ('Babysitters, The', 58.65, 658);
insert into products (title, price, inventory_count) values ('Fast & Furious (Fast and the Furious 4, The)', 34.07, 0);
insert into products (title, price, inventory_count) values ('Some Days Are Better Than Others', 4.82, 685);
insert into products (title, price, inventory_count) values ('White on Rice', 27.9, 7);
insert into products (title, price, inventory_count) values ('The Swedish Moment', 55.83, 313);
insert into products (title, price, inventory_count) values ('Dominion: Prequel to the Exorcist', 5.62, 0);
insert into products (title, price, inventory_count) values ('Out Cold', 7.08, 110);
insert into products (title, price, inventory_count) values ('Spiders, Part 2: The Diamond Ship, The (Die Spinnen, 2. Teil - Das Brillantenschiff)', 52.92, 0);
insert into products (title, price, inventory_count) values ('Into the Storm', 58.97, 0);
insert into products (title, price, inventory_count) values ('Romeo Must Die', 15.98, 965);
insert into products (title, price, inventory_count) values ('Some Folks Call It a Sling Blade', 3.81, 871);
insert into products (title, price, inventory_count) values ('Crackerjack', 65.04, 956);
insert into products (title, price, inventory_count) values ('Flubber', 8.74, 887);
insert into products (title, price, inventory_count) values ('Into the Night', 38.58, 0);
insert into products (title, price, inventory_count) values ('Plutonium Circus', 65.04, 688);
insert into products (title, price, inventory_count) values ('Kamchatka', 36.94, 504);
insert into products (title, price, inventory_count) values ('Rage in Heaven', 35.62, 749);
insert into products (title, price, inventory_count) values ('Head On', 11.19, 0);
insert into products (title, price, inventory_count) values ('Just Go with It', 37.66, 458);
insert into products (title, price, inventory_count) values ('Children Shouldn''t Play with Dead Things', 14.81, 0);
insert into products (title, price, inventory_count) values ('Escape to Athena', 61.75, 503);
insert into products (title, price, inventory_count) values ('Giant', 58.5, 0);
insert into products (title, price, inventory_count) values ('Let''s Do It Again', 35.59, 157);
insert into products (title, price, inventory_count) values ('Parting Glances', 50.48, 78);
insert into products (title, price, inventory_count) values ('Great K & A Train Robbery, The', 41.95, 422);
insert into products (title, price, inventory_count) values ('Z.P.G.', 56.98, 130);
insert into products (title, price, inventory_count) values ('Newcastle', 16.0, 838);
insert into products (title, price, inventory_count) values ('Chairman of the Board', 68.08, 491);
insert into products (title, price, inventory_count) values ('Evil Toons', 35.21, 36);
insert into products (title, price, inventory_count) values ('What''s Eating Gilbert Grape', 45.08, 51);
insert into products (title, price, inventory_count) values ('Waterloo Bridge', 55.29, 0);
insert into products (title, price, inventory_count) values ('Happy-Go-Lucky', 40.12, 622);
insert into products (title, price, inventory_count) values ('Prefab People, The (Panelkapcsolat)', 30.29, 116);
insert into products (title, price, inventory_count) values ('Caravaggio', 17.27, 0);
insert into products (title, price, inventory_count) values ('Made in America', 67.12, 69);
insert into products (title, price, inventory_count) values ('Apprenticeship of Duddy Kravitz, The', 15.67, 315);
insert into products (title, price, inventory_count) values ('Pretty Good for a Human (People Not as Bad as They Seem) (Aika hyvä ihmiseksi)', 29.31, 564);
insert into products (title, price, inventory_count) values ('Pekka ja Pätkä lumimiehen jäljillä', 12.94, 177);
insert into products (title, price, inventory_count) values ('Waking Ned Devine (a.k.a. Waking Ned)', 41.8, 783);
insert into products (title, price, inventory_count) values ('Little Colonel, The', 53.03, 0);
insert into products (title, price, inventory_count) values ('Generation War', 65.51, 35);
insert into products (title, price, inventory_count) values ('Race to Witch Mountain', 19.54, 304);
insert into products (title, price, inventory_count) values ('Lord of Tears', 64.03, 150);
insert into products (title, price, inventory_count) values ('Yes, But... (Oui, mais...)', 19.76, 643);
insert into products (title, price, inventory_count) values ('Marriage Retreat', 35.91, 0);
insert into products (title, price, inventory_count) values ('Altman', 55.48, 0);
insert into products (title, price, inventory_count) values ('Big Star: Nothing Can Hurt Me', 53.24, 102);
insert into products (title, price, inventory_count) values ('Hybrid', 31.58, 16);
insert into products (title, price, inventory_count) values ('Malibu''s Most Wanted', 12.41, 205);
insert into products (title, price, inventory_count) values ('Ballad of Cable Hogue, The', 6.86, 379);
insert into products (title, price, inventory_count) values ('Jesus Henry Christ', 31.63, 0);
insert into products (title, price, inventory_count) values ('Noose, The (Petla)', 68.04, 287);
insert into products (title, price, inventory_count) values ('Winged Creatures (Fragments)', 36.24, 856);
insert into products (title, price, inventory_count) values ('Happening, The', 60.01, 38);
insert into products (title, price, inventory_count) values ('Intended, The', 44.69, 80);
insert into products (title, price, inventory_count) values ('Thank God It''s Friday', 6.98, 0);
insert into products (title, price, inventory_count) values ('Shepherd of the Hills, The', 63.08, 0);
insert into products (title, price, inventory_count) values ('Passing Fancy (Dekigokoro)', 55.92, 24);
insert into products (title, price, inventory_count) values ('Best Intentions, The (Den goda viljan)', 28.59, 0);
insert into products (title, price, inventory_count) values ('Shriek If You Know What I Did Last Friday the Thirteenth', 22.74, 0);
insert into products (title, price, inventory_count) values ('Second Honeymoon', 11.66, 0);
insert into products (title, price, inventory_count) values ('Embracing', 42.12, 365);
insert into products (title, price, inventory_count) values ('Super Troopers', 61.61, 715);
insert into products (title, price, inventory_count) values ('Bigfoot Lives', 10.85, 631);
insert into products (title, price, inventory_count) values ('Hangin'' with the Homeboys', 56.42, 570);
insert into products (title, price, inventory_count) values ('Changing Sides (De l''autre côté du lit)', 60.0, 914);
insert into products (title, price, inventory_count) values ('Power of One, The', 19.43, 759);
insert into products (title, price, inventory_count) values ('Whale Rider', 27.28, 737);
insert into products (title, price, inventory_count) values ('Justice League: Doom ', 36.42, 95);
insert into products (title, price, inventory_count) values ('ATM', 68.95, 0);
insert into products (title, price, inventory_count) values ('Producers, The', 11.2, 238);
insert into products (title, price, inventory_count) values ('Nothing to Lose (a.k.a. Ten Benny)', 14.97, 0);
insert into products (title, price, inventory_count) values ('Windtalkers', 28.34, 810);
insert into products (title, price, inventory_count) values ('Fish Called Wanda, A', 48.78, 548);
insert into products (title, price, inventory_count) values ('Step Up', 56.39, 371);
insert into products (title, price, inventory_count) values ('Our Hospitality', 69.1, 500);
insert into products (title, price, inventory_count) values ('Around the World in 80 Days', 59.38, 219);
insert into products (title, price, inventory_count) values ('Adios Sabata', 40.67, 194);
insert into products (title, price, inventory_count) values ('Aurora', 7.2, 337);
insert into products (title, price, inventory_count) values ('50 Worst Movies Ever Made, The', 24.18, 685);
insert into products (title, price, inventory_count) values ('Smiley''s People', 3.09, 0);
insert into products (title, price, inventory_count) values ('Moving Violations', 56.95, 126);
insert into products (title, price, inventory_count) values ('Crippled Masters (Tian can di que)', 8.78, 779);
insert into products (title, price, inventory_count) values ('Be with Me', 48.35, 139);
insert into products (title, price, inventory_count) values ('Retroactive', 51.45, 473);
insert into products (title, price, inventory_count) values ('Ida', 24.68, 219);
insert into products (title, price, inventory_count) values ('Last Trapper, The (Le dernier trappeur)', 60.93, 132);
insert into products (title, price, inventory_count) values ('Merantau', 21.76, 628);
insert into products (title, price, inventory_count) values ('Nature of the Beast, The', 69.62, 0);
insert into products (title, price, inventory_count) values ('SpongeBob SquarePants Movie, The', 65.33, 993);
insert into products (title, price, inventory_count) values ('Black Nativity', 25.42, 0);
insert into products (title, price, inventory_count) values ('Memory of a Killer, The (Zaak Alzheimer, De)', 61.13, 969);
insert into products (title, price, inventory_count) values ('Burning Plain, The', 22.2, 0);
insert into products (title, price, inventory_count) values ('Eastern Drift (Indigène d''Eurasie)', 25.34, 815);
insert into products (title, price, inventory_count) values ('Quiet Duel, The (Shizukanaru ketto)', 11.76, 97);
insert into products (title, price, inventory_count) values ('Madhouse', 68.58, 175);
insert into products (title, price, inventory_count) values ('Salvatore Giuliano', 43.63, 758);
insert into products (title, price, inventory_count) values ('Personal Effects', 54.33, 951);
insert into products (title, price, inventory_count) values ('People Like Us', 52.09, 924);
insert into products (title, price, inventory_count) values ('Enron: The Smartest Guys in the Room', 17.72, 0);
insert into products (title, price, inventory_count) values ('Nursery University', 16.23, 124);
insert into products (title, price, inventory_count) values ('Karate Kid, The', 19.31, 798);
insert into products (title, price, inventory_count) values ('Together (Tillsammans)', 45.29, 0);
insert into products (title, price, inventory_count) values ('Popatopolis', 57.33, 0);
insert into products (title, price, inventory_count) values ('Wish You Were Here', 60.71, 0);
insert into products (title, price, inventory_count) values ('P.U.N.K.S', 29.93, 823);
insert into products (title, price, inventory_count) values ('Power Play', 49.24, 617);
insert into products (title, price, inventory_count) values ('Happy Accidents', 17.48, 285);
insert into products (title, price, inventory_count) values ('Love Songs (Les chansons d''amour)', 24.1, 986);
insert into products (title, price, inventory_count) values ('Daddy Day Camp', 22.86, 45);
insert into products (title, price, inventory_count) values ('Billy Madison', 26.81, 621);
insert into products (title, price, inventory_count) values ('AVP: Alien vs. Predator', 27.13, 0);
insert into products (title, price, inventory_count) values ('Instructions Not Included (No se Aceptan Devoluciones)', 52.99, 354);
insert into products (title, price, inventory_count) values ('Damn Yankees!', 43.09, 797);
insert into products (title, price, inventory_count) values ('Austin Powers: International Man of Mystery', 35.2, 0);
insert into products (title, price, inventory_count) values ('Blow-Up (Blowup)', 67.45, 90);
insert into products (title, price, inventory_count) values ('Mansfield Park', 16.07, 484);
insert into products (title, price, inventory_count) values ('Critters 3', 7.28, 0);
insert into products (title, price, inventory_count) values ('Notes on a Scandal', 40.78, 967);
insert into products (title, price, inventory_count) values ('Debt, The', 55.09, 980);
insert into products (title, price, inventory_count) values ('Troll in Central Park, A', 49.26, 321);
insert into products (title, price, inventory_count) values ('Flash Gordon', 6.68, 0);
insert into products (title, price, inventory_count) values ('Old Gringo', 12.12, 0);
insert into products (title, price, inventory_count) values ('Strategic Air Command', 60.99, 911);
insert into products (title, price, inventory_count) values ('Breaking Away', 64.96, 912);
insert into products (title, price, inventory_count) values ('Prisoner of Zenda, The', 22.92, 985);
insert into products (title, price, inventory_count) values ('Bionicle: Mask of Light (Bionicle: Mask of Light - The Movie)', 62.53, 407);
insert into products (title, price, inventory_count) values ('Broken Windows', 7.62, 169);
insert into products (title, price, inventory_count) values ('Carrington', 18.63, 3);
insert into products (title, price, inventory_count) values ('Seeking Justice', 63.97, 521);
insert into products (title, price, inventory_count) values ('Deer Hunter, The', 49.24, 197);
insert into products (title, price, inventory_count) values ('Sour Grapes', 12.84, 0);
insert into products (title, price, inventory_count) values ('Lucky Ones, The', 13.59, 321);
insert into products (title, price, inventory_count) values ('White God (Fehér isten)', 22.85, 13);
insert into products (title, price, inventory_count) values ('Endless Love', 21.64, 698);
insert into products (title, price, inventory_count) values ('Torpedo Run', 55.88, 228);
insert into products (title, price, inventory_count) values ('Two Bits', 28.58, 0);
insert into products (title, price, inventory_count) values ('Prophecy 3: The Ascent, The', 56.16, 0);
insert into products (title, price, inventory_count) values ('Effect of Gamma Rays on Man-in-the-Moon Marigolds, The', 39.41, 943);
insert into products (title, price, inventory_count) values ('L: Change the World', 50.12, 848);
insert into products (title, price, inventory_count) values ('4 Months, 3 Weeks and 2 Days (4 luni, 3 saptamâni si 2 zile)', 6.13, 0);
insert into products (title, price, inventory_count) values ('Someone I Loved (Je l''aimais)', 29.49, 648);
insert into products (title, price, inventory_count) values ('And Then There Was You', 47.06, 174);
insert into products (title, price, inventory_count) values ('Executive Decision', 18.84, 0);
insert into products (title, price, inventory_count) values ('Any Questions for Ben?', 39.47, 0);
insert into products (title, price, inventory_count) values ('Boy Eats Girl', 12.7, 38);
insert into products (title, price, inventory_count) values ('Map of the Human Heart', 58.05, 768);
insert into products (title, price, inventory_count) values ('Corruption (a.k.a. Carnage)', 53.31, 772);
insert into products (title, price, inventory_count) values ('Blue Umbrella, The', 28.26, 0);
insert into products (title, price, inventory_count) values ('Harrison Bergeron', 29.56, 283);
insert into products (title, price, inventory_count) values ('La Luna', 68.94, 320);
insert into products (title, price, inventory_count) values ('Dancing Outlaw II: Jesco Goes to Hollywood', 31.61, 0);
insert into products (title, price, inventory_count) values ('Travelling Salesman', 34.96, 0);
insert into products (title, price, inventory_count) values ('Limitless', 20.85, 0);
insert into products (title, price, inventory_count) values ('Making of a Legend: Gone with the Wind, The', 55.84, 553);
insert into products (title, price, inventory_count) values ('Last Time, The', 54.18, 559);
insert into products (title, price, inventory_count) values ('Dungeon Masters, The', 18.88, 845);
insert into products (title, price, inventory_count) values ('Separate Lies', 51.7, 775);
insert into products (title, price, inventory_count) values ('Ballad of Jack and Rose, The', 39.82, 0);
insert into products (title, price, inventory_count) values ('36 fillette', 41.04, 383);
insert into products (title, price, inventory_count) values ('Hits', 63.66, 984);
insert into products (title, price, inventory_count) values ('Escaflowne: The Movie (Escaflowne)', 52.12, 0);
insert into products (title, price, inventory_count) values ('Two Jakes, The', 29.54, 0);
insert into products (title, price, inventory_count) values ('Bullies', 22.29, 0);
insert into products (title, price, inventory_count) values ('Return of the Living Dead 3', 15.44, 858);
insert into products (title, price, inventory_count) values ('Love Happens', 16.57, 345);
insert into products (title, price, inventory_count) values ('Km. 0 - Kilometer Zero (Kilómetro cero)', 8.88, 507);
insert into products (title, price, inventory_count) values ('JLG/JLG (JLG/JLG - autoportrait de décembre)', 45.44, 926);
insert into products (title, price, inventory_count) values ('Jade Warrior (Jadesoturi)', 21.2, 0);
insert into products (title, price, inventory_count) values ('Babyfever', 5.22, 534);
insert into products (title, price, inventory_count) values ('Paul Blart: Mall Cop', 55.58, 704);
insert into products (title, price, inventory_count) values ('Enemy at the Gates', 28.36, 761);
insert into products (title, price, inventory_count) values ('Alien Abduction', 36.85, 470);
insert into products (title, price, inventory_count) values ('Interstate 60', 56.55, 651);
insert into products (title, price, inventory_count) values ('Good Humor Man, The', 28.84, 35);
insert into products (title, price, inventory_count) values ('Dune', 32.53, 903);
insert into products (title, price, inventory_count) values ('Manrape (Män kan inte våldtas) ', 65.72, 151);
